sonar.projectKey=gearbox_aisha
sonar.organization=gearbox

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=aisha

sonar.python.version=3.10,3.11,3.12

sonar.sources=src
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml

# Exclude third-party and configs from analysis
sonar.exclusions=.github/**/*,docs/**/*

sonar.sourceEncoding=UTF-8
